/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package userinterface;

import classes.db.DbAnggotaKelas;
import classes.db.DbMahasiswa;
import classes.db.DbMataKuliah;
import classes.entity.AnggotaKelas;
import classes.entity.Kelas;
import classes.entity.Mahasiswa;
import classes.entity.MataKuliah;
import java.beans.PropertyVetoException;
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Angga Suta Dharmawan - 16101650
 */
public class FrmAnggotaKelas extends javax.swing.JInternalFrame {

    /** Creates new form FrmRombel */
    private DefaultTableModel modelMhs;
    private DefaultTableModel modelTerdaftar;
    Kelas kelas = new Kelas();
    
    public FrmAnggotaKelas(Kelas kls) {
        initComponents();
        
        modelMhs = new DefaultTableModel();
        modelTerdaftar = new DefaultTableModel();
        
        modelMhs.addColumn("No");
        modelMhs.addColumn("Nim");
        modelMhs.addColumn("Nama");
        tableMahasiswa.setModel(modelMhs);
        tableMahasiswa.getColumnModel().getColumn(0).setPreferredWidth(10);
        tableMahasiswa.getColumnModel().getColumn(1).setPreferredWidth(7);
        //tableMahasiswa.getColumnModel().getColumn(2).setPreferredWidth(9);
        
        modelTerdaftar.addColumn("No");
        modelTerdaftar.addColumn("Nim");
        modelTerdaftar.addColumn("Nama");
        tableTerdaftar.setModel(modelTerdaftar);
        tableTerdaftar.getColumnModel().getColumn(0).setPreferredWidth(4);
        tableTerdaftar.getColumnModel().getColumn(1).setPreferredWidth(10);
        //tableTerdaftar.getColumnModel().getColumn(2).setPreferredWidth(9);
        
        this.kelas = kls;
        
        String strMataKuliah = "";
        try{
            MataKuliah matkul = DbMataKuliah.tampilByKode(kelas.getKodeMataKuliah());
            strMataKuliah = matkul.getNama();
        }catch(Exception e){}
        txtKelas.setText(kelas.getKode() + " / " + kelas.getNama() + " / " + strMataKuliah + " / "+ ((kelas.getJamMulai()<10 ? "0" + kelas.getJamMulai() : kelas.getJamMulai()) + ":" + (kelas.getMenitMulai()<10 ? "0" + kelas.getMenitMulai() : kelas.getMenitMulai()) + " - " + (kelas.getJamBerakhir()<10 ? "0" + kelas.getJamBerakhir(): kelas.getJamBerakhir()) + ":" + (kelas.getMenitBerakhir()<10 ? "0" + kelas.getMenitBerakhir() : kelas.getMenitBerakhir())) +"");
        txtKelas.setEditable(false);
        
        isiMahasiswa();
        isiTerdaftar();
        
    }
    
    public void isiTerdaftar(){
        modelTerdaftar.getDataVector().removeAllElements();
        modelTerdaftar.fireTableDataChanged();
        ArrayList lisTerdaftar = new ArrayList();
        try{
            lisTerdaftar = DbMahasiswa.tampil(0, 0, "nim in (select ak.nim from anggota_kelas ak where ak.kode_kelas='"+ kelas.getKode() +"')", "nama asc");
            if(lisTerdaftar!=null && lisTerdaftar.size()>0){
                for(int i = 0; i < lisTerdaftar.size(); i++){
                    Mahasiswa mhs = (Mahasiswa) lisTerdaftar.get(i);
                    Object[] o = new Object[3];
                    o[0] = (i+1);
                    o[1] = mhs.getNim();
                    o[2] = mhs.getNama();
                    modelTerdaftar.addRow(o);
                }
            }
        }catch(Exception e){e.printStackTrace();}
    }
    
    public void isiMahasiswa(){
        modelMhs.getDataVector().removeAllElements();
        modelMhs.fireTableDataChanged();
        ArrayList listMhs = new ArrayList();
        try{
            listMhs = DbMahasiswa.tampil(0, 0, "nim not in (select ak.nim from anggota_kelas ak inner join kelas k on ak.kode_kelas=k.kode "
                                                +" where k.kode_matakuliah='"+ kelas.getKodeMataKuliah() +"')", "nama asc");
            if(listMhs!=null && listMhs.size()>0){
                for(int i = 0; i < listMhs.size(); i++){
                    Mahasiswa mhs = (Mahasiswa) listMhs.get(i);
                    Object[] o = new Object[3];
                    o[0] = (i+1);
                    o[1] = mhs.getNim();
                    o[2] = mhs.getNama();
                    modelMhs.addRow(o);
                }
            }
        }catch(Exception e){e.printStackTrace();}
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtKelas = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableMahasiswa = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tableTerdaftar = new javax.swing.JTable();
        jLabel4 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        cmdAdd = new javax.swing.JButton();
        cmdRemove = new javax.swing.JButton();
        cmdBatal = new javax.swing.JButton();

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setText("Kelas");

        txtKelas.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N

        tableMahasiswa.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tableMahasiswa);

        jLabel2.setText("Mahasiswa Tanpa Kelas");

        jLabel3.setText("Mahasiswa Terdaftar");

        tableTerdaftar.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(tableTerdaftar);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel4.setText("Mahasiswa Terdaftar");

        jButton1.setText("Simpan Kelas");

        cmdAdd.setText(">>");
        cmdAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdAddActionPerformed(evt);
            }
        });

        cmdRemove.setText("<<");
        cmdRemove.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdRemoveActionPerformed(evt);
            }
        });

        cmdBatal.setText("Batal");
        cmdBatal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdBatalActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel4)
                        .addGap(10, 10, 10))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtKelas, javax.swing.GroupLayout.PREFERRED_SIZE, 610, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 282, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel2))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(45, 45, 45)
                                        .addComponent(jLabel3))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(6, 6, 6)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(cmdAdd)
                                            .addComponent(cmdRemove))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 308, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cmdBatal)
                .addGap(30, 30, 30))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addGap(2, 2, 2)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtKelas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(114, 114, 114)
                        .addComponent(cmdAdd)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cmdRemove))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 342, Short.MAX_VALUE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(cmdBatal))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cmdBatalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdBatalActionPerformed
        try {
            FrmMain.openForm(new FrmKelas(), "Form Kelas");
            this.setClosed(true);
        } catch (PropertyVetoException ex) {
        }
    }//GEN-LAST:event_cmdBatalActionPerformed

    private void cmdAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdAddActionPerformed
        // simpan mahasiswa ke dalam anggota kelas
        //inisialisasi table yang terseleksi
        int[] selectedRows = new int[tableMahasiswa.getSelectedRows().length];
        //tampung di variable selected rows
        selectedRows = tableMahasiswa.getSelectedRows();
        
        //looping ambil baris keberapa yang terseleksi
        for(int i = 0; i < selectedRows.length; i++){
            //simpan ke anggota
            AnggotaKelas anggota = new AnggotaKelas();
            anggota.setKodeKelas(kelas.getKode());
            anggota.setNim(String.valueOf(tableMahasiswa.getValueAt(selectedRows[i], 1)));
            try{
                DbAnggotaKelas.simpanData(anggota);
            }catch(Exception e){e.printStackTrace();}
        }
        
        isiMahasiswa();
        isiTerdaftar();
    }//GEN-LAST:event_cmdAddActionPerformed

    private void cmdRemoveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdRemoveActionPerformed
        // hapus mahasiswa dari anggota kelas
        //inisialisasi table yang terseleksi
        int[] selectedRows = new int[tableTerdaftar.getSelectedRows().length];
        //tampung di variable selected rows
        selectedRows = tableTerdaftar.getSelectedRows();
        
        //looping ambil baris keberapa yang terseleksi
        for(int i = 0; i < selectedRows.length; i++){
            //simpan ke anggota
            AnggotaKelas anggota = new AnggotaKelas();
            anggota.setKodeKelas(kelas.getKode());
            anggota.setNim(String.valueOf(tableTerdaftar.getValueAt(selectedRows[i], 1)));
            try{
                DbAnggotaKelas.deleteData(anggota);
            }catch(Exception e){e.printStackTrace();}
        }
        
        isiMahasiswa();
        isiTerdaftar();
    }//GEN-LAST:event_cmdRemoveActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cmdAdd;
    private javax.swing.JButton cmdBatal;
    private javax.swing.JButton cmdRemove;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tableMahasiswa;
    private javax.swing.JTable tableTerdaftar;
    private javax.swing.JTextField txtKelas;
    // End of variables declaration//GEN-END:variables

}
