/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface;

import classes.db.DbDosen;
import classes.db.DbMataKuliah;
import classes.entity.Dosen;
import classes.entity.MataKuliah;
import java.beans.PropertyVetoException;
import java.util.ArrayList;
import java.util.Vector;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Angga Suta Dharmawan 16101650
 */

public class FrmDosen extends javax.swing.JInternalFrame {

    /**
     * Creates new form FrmDosen
     */
    private DefaultTableModel model;
    // penanda untuk operasi edit apa buat baru
    boolean isEdit = false;

    // var untuk menyimpan kode lama, jika seandainya kodenya diganti
    String kodeOld = "";


    public FrmDosen() {
        initComponents();
        
        model = new DefaultTableModel();
        model.addColumn("NIDN");       
        model.addColumn("Nama Dosen");
        model.addColumn("Jenis Kelamin");
        
        tableDosen.setModel(model);
        tableDosen.getColumnModel().getColumn(0).setPreferredWidth(30);
        tableDosen.getColumnModel().getColumn(1).setPreferredWidth(170);
        tableDosen.getColumnModel().getColumn(2).setPreferredWidth(50);
        
        loadData();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cmdKeluar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtNidn = new javax.swing.JTextField();
        txtNama = new javax.swing.JTextField();
        rLakiLaki = new javax.swing.JRadioButton();
        rPerempuan = new javax.swing.JRadioButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableDosen = new javax.swing.JTable();
        cmdTambah = new javax.swing.JButton();
        cmdSimpan = new javax.swing.JButton();

        setBorder(javax.swing.BorderFactory.createEtchedBorder());

        cmdKeluar.setText("Keluar");
        cmdKeluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdKeluarActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("D o s e n");

        jLabel2.setText("NIDN");

        jLabel3.setText("Nama");

        jLabel4.setText("Jenis Kelamin");

        rLakiLaki.setText("Laki - Laki");

        rPerempuan.setText("Perempuan");

        tableDosen.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tableDosen.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableDosenMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tableDosen);

        cmdTambah.setText("Tambah");
        cmdTambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdTambahActionPerformed(evt);
            }
        });

        cmdSimpan.setText("Simpan");
        cmdSimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdSimpanActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 500, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4))
                        .addGap(28, 28, 28)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(rLakiLaki)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(rPerempuan))
                            .addComponent(txtNidn, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtNama, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(cmdTambah)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cmdSimpan)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(cmdKeluar)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(txtNidn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(txtNama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(25, 25, 25))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel4)
                        .addComponent(rLakiLaki)
                        .addComponent(rPerempuan)))
                .addGap(9, 9, 9)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 269, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmdKeluar)
                    .addComponent(cmdTambah)
                    .addComponent(cmdSimpan))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void loadData(){
        model.getDataVector().removeAllElements();
        model.fireTableDataChanged();
        
        ArrayList vDosen = new ArrayList();
        try{
            vDosen = DbDosen.tampil(0, 0, "", "nidn asc");
            if(vDosen!=null && vDosen.size()>0){
                for(int i=0; i<vDosen.size(); i++){
                    Dosen dosen = (Dosen) vDosen.get(i);
                    Object[] o = new Object[4];
                    o[0] = dosen.getNidn();
                    o[1] = dosen.getNama();
                    String jenisKelamin = "Laki-laki";
                    if(dosen.getJenisKelamin().equalsIgnoreCase("P")){
                        jenisKelamin = "Perempuan";
                    }
                    o[2] = jenisKelamin;
                    model.addRow(o);
                }
            }
        }catch(Exception e){
            e.printStackTrace();
        }
    }
    
    public void kosongkanData(){
        isEdit = false;
        txtNidn.setText("");
        txtNama.setText("");
    }
    
    private void cmdKeluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdKeluarActionPerformed
        try {
            this.setClosed(true);
        } catch (PropertyVetoException ex) {
        }
    }//GEN-LAST:event_cmdKeluarActionPerformed

    private void cmdTambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdTambahActionPerformed
        kosongkanData();
    }//GEN-LAST:event_cmdTambahActionPerformed

    private void cmdSimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdSimpanActionPerformed
        boolean success = false;
        if(txtNama.getText().length()<=0 || txtNidn.getText().length()<=0){
            JOptionPane.showMessageDialog(null, "Nidn dan Nama tidak boleh kosong", "Perhatian", JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        //ambil data dari form
        Dosen dosen = new Dosen();
        dosen.setNidn(txtNidn.getText());
        dosen.setNama(txtNama.getText());
        String jenisKelamin = "L";
        if(rPerempuan.isSelected()){
            jenisKelamin = "P";
        }
        dosen.setJenisKelamin(jenisKelamin);
        
        //simpan data dengan method simpandata
        success = DbDosen.simpanData(isEdit, kodeOld, dosen);
        if(success){
            JOptionPane.showMessageDialog(null, "Data berhasil disimpan...", "Informasi", JOptionPane.INFORMATION_MESSAGE);
            kosongkanData();
            loadData();
        }
    }//GEN-LAST:event_cmdSimpanActionPerformed

    private void tableDosenMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableDosenMouseClicked
        int selected = tableDosen.getSelectedRow();
        if(selected==-1){
            return;
        }
        
        isEdit = true;
        kodeOld = (String) model.getValueAt(selected, 0);
        txtNidn.setText(kodeOld);
        txtNama.setText((String) model.getValueAt(selected, 1));
        if(String.valueOf(model.getValueAt(selected, 2)).equalsIgnoreCase("Laki-laki")){
            rLakiLaki.setSelected(true);
            rPerempuan.setSelected(false);
        }else{
            rLakiLaki.setSelected(false);
            rPerempuan.setSelected(true);
        }
    }//GEN-LAST:event_tableDosenMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cmdKeluar;
    private javax.swing.JButton cmdSimpan;
    private javax.swing.JButton cmdTambah;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JRadioButton rLakiLaki;
    private javax.swing.JRadioButton rPerempuan;
    private javax.swing.JTable tableDosen;
    private javax.swing.JTextField txtNama;
    private javax.swing.JTextField txtNidn;
    // End of variables declaration//GEN-END:variables
}
