/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface;

import classes.db.DbDosen;
import classes.db.DbKelas;
import classes.db.DbMahasiswa;
import classes.db.DbMataKuliah;
import classes.entity.Dosen;
import classes.entity.Kelas;
import classes.entity.MataKuliah;
import java.beans.PropertyVetoException;
import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author oxysystem
 */
public class FrmKelasDetail extends javax.swing.JInternalFrame {

    /**
     * Creates new form FrmKelasDetail
     */
    public String kodeOld = "";
    Kelas kelas = new Kelas();
    
    public FrmKelasDetail(String kodeKelas) {
        initComponents();
        isiListWaktu();
        isiListMataKuliah();
        isiListDosen();
        
        System.out.println("kode : " + kodeKelas);
        if(kodeKelas.length()>0){
            kelas = DbKelas.tampilByKode(kodeKelas);
            kodeOld = kelas.getKode();
            this.txtKode.setEditable(false);
            loadData();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cmdBatal = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtKode = new javax.swing.JTextField();
        txtNama = new javax.swing.JTextField();
        cmbMataKuliah = new javax.swing.JComboBox<>();
        cmbDosen = new javax.swing.JComboBox<>();
        cmbHari = new javax.swing.JComboBox<>();
        cmbJamMulai = new javax.swing.JComboBox<>();
        cmbMenitMulai = new javax.swing.JComboBox<>();
        jLabel9 = new javax.swing.JLabel();
        cmbMenitBerakhir = new javax.swing.JComboBox<>();
        cmbJamBerakhir = new javax.swing.JComboBox<>();
        txtRuangan = new javax.swing.JTextField();
        cmdSimpan = new javax.swing.JButton();

        cmdBatal.setText("Batal");
        cmdBatal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdBatalActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        jLabel1.setText("Kelas Detail");

        jLabel2.setText("Kode");

        jLabel3.setText("Nama");

        jLabel4.setText("Mata Kuliah");

        jLabel5.setText("Dosen");

        jLabel6.setText("Hari");

        jLabel7.setText("Waktu");

        jLabel8.setText("Ruangan");

        cmbMataKuliah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbMataKuliahActionPerformed(evt);
            }
        });

        cmbHari.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Senin", "Selasa", "Rabu", "Kamis", "Jumat", "Sabtu", "Minggu", " " }));

        jLabel9.setText("sampai");

        cmdSimpan.setText("Simpan");
        cmdSimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdSimpanActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8)
                            .addComponent(jLabel4))
                        .addGap(29, 29, 29)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(cmbHari, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(txtRuangan, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addComponent(cmbJamMulai, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(cmbMenitMulai, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel9)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cmbJamBerakhir, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cmbMenitBerakhir, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(cmbMataKuliah, 0, 396, Short.MAX_VALUE)
                            .addComponent(cmbDosen, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jLabel1))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(cmdSimpan)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(cmdBatal)))
                        .addGap(12, 12, 12))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3))
                        .addGap(58, 58, 58)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtKode, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txtNama)
                                .addContainerGap())))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(2, 2, 2)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtKode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtNama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(5, 5, 5)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(cmbMataKuliah, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(8, 8, 8)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(cmbDosen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel5))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cmbHari, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmbJamMulai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(cmbMenitMulai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9)
                    .addComponent(cmbJamBerakhir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmbMenitBerakhir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(txtRuangan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 23, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmdBatal)
                    .addComponent(cmdSimpan))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    public void loadData(){
        if( kelas.getKode().length()>0){
            txtKode.setText(kelas.getKode());
            txtKode.setEditable(false);
            txtNama.setText(kelas.getNama());
            
            MataKuliah mataKuliah = new MataKuliah();
            try{
                mataKuliah = DbMataKuliah.tampilByKode(kelas.getKodeMataKuliah());
            }catch(Exception e){}
            
            cmbMataKuliah.setSelectedItem(mataKuliah.getNama());
            
            Dosen dosen = new Dosen();
            try{
                dosen = DbDosen.tampilByNidn(kelas.getNidn());
            }catch(Exception e){}
            
            cmbDosen.setSelectedItem(dosen.getNama());
            cmbHari.setSelectedItem(kelas.getHari());
            
            String strJamMulai = String.valueOf(kelas.getJamMulai()<10 ? "0" + kelas.getJamMulai() : kelas.getJamMulai());
            String strMenitMulai = String.valueOf(kelas.getMenitMulai()<10 ? "0" + kelas.getMenitMulai() : kelas.getMenitMulai());
            String strJamBerakhir = String.valueOf(kelas.getJamBerakhir()<10 ? "0" + kelas.getJamBerakhir() : kelas.getJamBerakhir());
            String strMenitBerakhir = String.valueOf(kelas.getMenitBerakhir()<10 ? "0" + kelas.getMenitBerakhir() : kelas.getMenitBerakhir());
            cmbJamMulai.setSelectedItem(strJamMulai);
            cmbMenitMulai.setSelectedItem(strMenitMulai);
            cmbJamBerakhir.setSelectedItem(strJamBerakhir);
            cmbMenitBerakhir.setSelectedItem(strMenitBerakhir);
            txtRuangan.setText(kelas.getRuangan());
            
        }
    }
    
    public void isiListDosen(){
        ArrayList listDosen = new ArrayList();
        try{
            listDosen = DbDosen.tampil(0, 0, "", "nama asc");
            if(listDosen.size()>0){
                for(int i = 0; i < listDosen.size(); i++){
                    Dosen dosen = (Dosen) listDosen.get(i);
                    cmbDosen.addItem(dosen.getNama());
                }
            }else{
                cmbDosen.addItem("- tidak ada dosen -");
            }
        }catch(Exception e){}
        
    }
    
    public void isiListMataKuliah(){
        ArrayList listMataKuliah = new ArrayList();
        try{
            listMataKuliah = DbMataKuliah.tampil(0, 0, "", "nama asc");
            if(listMataKuliah.size()>0){
                for(int i = 0; i<listMataKuliah.size(); i++){
                    MataKuliah mataKuliah = (MataKuliah) listMataKuliah.get(i);
                    cmbMataKuliah.addItem(mataKuliah.getNama());
                }
            }else{
                cmbMataKuliah.addItem("- tidak ada mata kuliah -");
            }
        }catch(Exception e){}
        
    }
    
    public void isiListWaktu(){
        //mengisi jam
        for(int jam=0; jam<=23; jam++){
            String strJam = "0" + String.valueOf(jam);
            if(jam>9) strJam = String.valueOf(jam);
            
            cmbJamMulai.addItem(strJam);
            cmbJamBerakhir.addItem(strJam);
        }
        
        //mengisi menit
        for(int menit=0; menit<=59; menit++){
            String strMenit = "0" + String.valueOf(menit);
            if(menit>9) strMenit = String.valueOf(menit);
            
            cmbMenitMulai.addItem(strMenit);
            cmbMenitBerakhir.addItem(strMenit);
        }
    }
    
    private void cmdBatalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdBatalActionPerformed
        try {
            FrmMain.openForm(new FrmKelas(), "Form Kelas");
            this.setClosed(true);
        } catch (PropertyVetoException ex) {
        }
    }//GEN-LAST:event_cmdBatalActionPerformed

    private void cmbMataKuliahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbMataKuliahActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbMataKuliahActionPerformed

    private void cmdSimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdSimpanActionPerformed
        if(txtKode.getText().length()<=0){
            JOptionPane.showMessageDialog(null, "Nim wajib diisi", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        kelas.setKode(txtKode.getText());
        kelas.setNama(txtNama.getText());
        
        MataKuliah mataKuliah = new MataKuliah();
        try{
            mataKuliah = DbMataKuliah.tampilByNama(String.valueOf(cmbMataKuliah.getSelectedItem()));
        }catch(Exception e){}
        kelas.setKodeMataKuliah(mataKuliah.getKode());
        
        Dosen dosen = new Dosen();
        try{
            dosen = DbDosen.tampilByNama(String.valueOf(cmbDosen.getSelectedItem()));
        }catch(Exception e){}
        kelas.setNidn(dosen.getNidn());
        
        kelas.setHari(String.valueOf(cmbHari.getSelectedItem()));
        
        kelas.setJamMulai(Integer.parseInt(String.valueOf(cmbJamMulai.getSelectedItem())));
        kelas.setMenitMulai(Integer.parseInt(String.valueOf(cmbMenitMulai.getSelectedItem())));
        
        kelas.setJamBerakhir(Integer.parseInt(String.valueOf(cmbJamBerakhir.getSelectedItem())));
        kelas.setMenitBerakhir(Integer.parseInt(String.valueOf(cmbMenitBerakhir.getSelectedItem())));
        
        kelas.setRuangan(txtRuangan.getText());
        
        boolean isSaved = DbKelas.simpanData(kodeOld, kelas);
        if(isSaved){
            JOptionPane.showMessageDialog(null, "Data berhasil disimpan", "Infomasi", JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_cmdSimpanActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cmbDosen;
    private javax.swing.JComboBox<String> cmbHari;
    private javax.swing.JComboBox<String> cmbJamBerakhir;
    private javax.swing.JComboBox<String> cmbJamMulai;
    private javax.swing.JComboBox<String> cmbMataKuliah;
    private javax.swing.JComboBox<String> cmbMenitBerakhir;
    private javax.swing.JComboBox<String> cmbMenitMulai;
    private javax.swing.JButton cmdBatal;
    private javax.swing.JButton cmdSimpan;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField txtKode;
    private javax.swing.JTextField txtNama;
    private javax.swing.JTextField txtRuangan;
    // End of variables declaration//GEN-END:variables
}
