/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface;

import classes.db.DbMahasiswa;
import classes.entity.Mahasiswa;
import java.beans.PropertyVetoException;
import java.util.Date;
import javax.swing.JOptionPane;

/**
 *
 * @author OxysystemPC
 */
public class FrmMahasiswaDetail extends javax.swing.JInternalFrame {

    /**
     * Creates new form FrmMahasiswaDetail
     */
    public String nimOld = "";
    public Mahasiswa mahasiswa = new Mahasiswa();
    
    public FrmMahasiswaDetail(String nim) {
        initComponents();
        this.nimOld = nim;
        
        //check edit or add new
        if(nim.length()>0){
            // ini jika edit maka ambil mahasiswa dari database berdasarkan nim
            mahasiswa = DbMahasiswa.tampilByNim(nim);
        }
        
        //tampilkan data ke form
        loadData();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        txtNim = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txtNama = new javax.swing.JTextField();
        txtTempatLahir = new javax.swing.JTextField();
        txtTanggalLahir = new javax.swing.JFormattedTextField();
        rLakiLaki = new javax.swing.JRadioButton();
        rPerempuan = new javax.swing.JRadioButton();
        txtProdi = new javax.swing.JComboBox<>();
        txtJurusan = new javax.swing.JComboBox<>();
        txtTahunMasuk = new javax.swing.JTextField();
        cmdBatal = new javax.swing.JButton();
        cmdSimpan = new javax.swing.JButton();

        setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("M a h a s i s w a");

        jLabel1.setText("NIM");

        jLabel3.setText("Nama Lengkap");

        jLabel4.setText("Tempat Lahir");

        jLabel5.setText("Tanggal Lahir");

        jLabel6.setText("Jenis Kelamin");

        jLabel7.setText("Program Studi");

        jLabel8.setText("Jurusan");

        jLabel9.setText("Tahun Masuk");

        txtTanggalLahir.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(new java.text.SimpleDateFormat("dd/MM/yyyy"))));

        rLakiLaki.setText("Laki - laki");
        rLakiLaki.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                rLakiLakiItemStateChanged(evt);
            }
        });
        rLakiLaki.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rLakiLakiActionPerformed(evt);
            }
        });

        rPerempuan.setText("Perempuan");
        rPerempuan.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                rPerempuanStateChanged(evt);
            }
        });

        txtProdi.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Teknik Informatika", "Sistem Komputer" }));
        txtProdi.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                txtProdiItemStateChanged(evt);
            }
        });
        txtProdi.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
            }
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
                txtProdiInputMethodTextChanged(evt);
            }
        });

        txtJurusan.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "MDI", "DGM", "KAB" }));

        cmdBatal.setText("Batal");
        cmdBatal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdBatalActionPerformed(evt);
            }
        });

        cmdSimpan.setText("Simpan");
        cmdSimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdSimpanActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(cmdSimpan)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cmdBatal))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8)
                            .addComponent(jLabel9))
                        .addGap(31, 31, 31)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtProdi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtTanggalLahir, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtTempatLahir, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtNama, javax.swing.GroupLayout.PREFERRED_SIZE, 306, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtNim, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(txtJurusan, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(txtTahunMasuk, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(rLakiLaki, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(18, 18, 18)
                                .addComponent(rPerempuan)))))
                .addContainerGap(17, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtNim, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtNama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtTempatLahir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtTanggalLahir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(5, 5, 5)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(rLakiLaki)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel6)
                        .addComponent(rPerempuan)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(txtProdi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(txtJurusan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(txtTahunMasuk, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmdBatal)
                    .addComponent(cmdSimpan))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void loadData(){
        if(mahasiswa.getNim().length()>0){
            //jika dia edit maka tampilkan data di text field dan lain lain
            txtNim.setText(mahasiswa.getNim());
            txtNama.setText(mahasiswa.getNama());
            txtTempatLahir.setText(mahasiswa.getTempatLahir());
            txtTanggalLahir.setValue(mahasiswa.getTanggalLahir());
            if(mahasiswa.getJenisKelamin().equalsIgnoreCase("L")){
                rLakiLaki.setSelected(true);
            }else{
                rPerempuan.setSelected(true);
            }
            
            txtProdi.setSelectedItem(mahasiswa.getProgramStudi());
            txtJurusan.setSelectedItem(mahasiswa.getJurusan());
            
            txtTahunMasuk.setText(String.valueOf(mahasiswa.getTahunMasuk()));
        }
    }
    
    private void cmdBatalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdBatalActionPerformed
        try {
            this.setClosed(true);
        } catch (PropertyVetoException ex) {
        }
        FrmMain.openForm(new FrmMahasiswa(), "Form Mahasiswa");
    }//GEN-LAST:event_cmdBatalActionPerformed

    private void txtProdiInputMethodTextChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_txtProdiInputMethodTextChanged
        
    }//GEN-LAST:event_txtProdiInputMethodTextChanged

    private void txtProdiItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_txtProdiItemStateChanged
        String selected = txtProdi.getModel().getSelectedItem().toString();
        txtJurusan.removeAllItems();
        if(selected.equalsIgnoreCase("Sistem Komputer")){
            txtJurusan.addItem("SK");
        }else{
            txtJurusan.addItem("MDI");
            txtJurusan.addItem("DGM");
            txtJurusan.addItem("KAB");
        }
        //JOptionPane.showMessageDialog(rootPane, "berubah");
    }//GEN-LAST:event_txtProdiItemStateChanged

    private void rLakiLakiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rLakiLakiActionPerformed
        
    }//GEN-LAST:event_rLakiLakiActionPerformed

    private void rLakiLakiItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_rLakiLakiItemStateChanged
        if(rLakiLaki.isSelected()){
            rPerempuan.setSelected(false);
        }
    }//GEN-LAST:event_rLakiLakiItemStateChanged

    private void rPerempuanStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_rPerempuanStateChanged
        if(rPerempuan.isSelected()){
            rLakiLaki.setSelected(false);
        }
    }//GEN-LAST:event_rPerempuanStateChanged

    private void cmdSimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdSimpanActionPerformed
        if(txtNim.getText().length()<=0){
            JOptionPane.showMessageDialog(null, "Nim wajib diisi", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        mahasiswa.setNim(txtNim.getText());
        mahasiswa.setNama(txtNama.getText());
        mahasiswa.setTempatLahir(txtTempatLahir.getText());
        mahasiswa.setTanggalLahir((Date) txtTanggalLahir.getValue());
        String jenisKelamin = "P";
        if(rLakiLaki.isSelected()){
            jenisKelamin = "L";
        }
        mahasiswa.setJenisKelamin(jenisKelamin);
        mahasiswa.setProgramStudi(txtProdi.getSelectedItem().toString());
        mahasiswa.setJurusan(txtJurusan.getSelectedItem().toString());
        mahasiswa.setTahunMasuk(Integer.parseInt(txtTahunMasuk.getText()));
        boolean isSaved = DbMahasiswa.simpanData(nimOld, mahasiswa);
        if(isSaved){
            JOptionPane.showMessageDialog(null, "Data berhasil disimpan", "Infomasi", JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_cmdSimpanActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton cmdBatal;
    private javax.swing.JButton cmdSimpan;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JRadioButton rLakiLaki;
    private javax.swing.JRadioButton rPerempuan;
    private javax.swing.JComboBox<String> txtJurusan;
    private javax.swing.JTextField txtNama;
    private javax.swing.JTextField txtNim;
    private javax.swing.JComboBox<String> txtProdi;
    private javax.swing.JTextField txtTahunMasuk;
    private javax.swing.JFormattedTextField txtTanggalLahir;
    private javax.swing.JTextField txtTempatLahir;
    // End of variables declaration//GEN-END:variables
}
