/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface;

import classes.db.DbMahasiswa;
import classes.entity.Mahasiswa;
import java.beans.PropertyVetoException;
import java.util.ArrayList;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author OxysystemPC
 */
public class FrmMahasiswa extends javax.swing.JInternalFrame {

    /**
     * Creates new form FrmMahasiswa2
     */
    
    private DefaultTableModel model;
    
    public FrmMahasiswa() {
        initComponents();
        
        model = new DefaultTableModel();
        model.addColumn("Nim");       
        model.addColumn("Nama");
        model.addColumn("Jenis Kelamin");
        model.addColumn("Program Studi");
        model.addColumn("Jurusan");
        
        tableMahasiswa.setModel(model);
        tableMahasiswa.getColumnModel().getColumn(0).setPreferredWidth(30);
        tableMahasiswa.getColumnModel().getColumn(1).setPreferredWidth(170);
        tableMahasiswa.getColumnModel().getColumn(2).setPreferredWidth(50);
        tableMahasiswa.getColumnModel().getColumn(3).setPreferredWidth(50);
        tableMahasiswa.getColumnModel().getColumn(4).setPreferredWidth(50);
        
        loadData();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableMahasiswa = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        txtCari = new javax.swing.JTextField();
        cmdCari = new javax.swing.JButton();
        cmdKeluar1 = new javax.swing.JButton();
        cmdTambah = new javax.swing.JButton();
        cmdHapus = new javax.swing.JButton();
        cmdUbah = new javax.swing.JButton();

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("M a h a s i s w a");

        tableMahasiswa.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tableMahasiswa);

        jLabel1.setText("Pencarian Nama");

        cmdCari.setText("Cari!");
        cmdCari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdCariActionPerformed(evt);
            }
        });

        cmdKeluar1.setText("Keluar");
        cmdKeluar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdKeluar1ActionPerformed(evt);
            }
        });

        cmdTambah.setText("Tambah");
        cmdTambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdTambahActionPerformed(evt);
            }
        });

        cmdHapus.setText("Hapus");
        cmdHapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdHapusActionPerformed(evt);
            }
        });

        cmdUbah.setText("Ubah");
        cmdUbah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdUbahActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 669, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(txtCari, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cmdCari))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(cmdTambah)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cmdUbah)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cmdHapus)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(cmdKeluar1)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(16, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtCari, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmdCari)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 407, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmdKeluar1)
                    .addComponent(cmdTambah)
                    .addComponent(cmdHapus)
                    .addComponent(cmdUbah))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void loadData(){
        model.getDataVector().removeAllElements();
        model.fireTableDataChanged();

        ArrayList vMahasiswa = new ArrayList();
        try{
            vMahasiswa = DbMahasiswa.tampil(0, 0, "nim like '%"+ txtCari.getText().trim() +"%' or nama like '%"+ txtCari.getText().trim() +"%'", "");
            if(vMahasiswa!=null && vMahasiswa.size()>0){
                for(int i=0; i<vMahasiswa.size(); i++){
                    Mahasiswa mahasiswa = (Mahasiswa) vMahasiswa.get(i);
                    Object[] o = new Object[5];
                    o[0] = mahasiswa.getNim();
                    o[1] = mahasiswa.getNama();
                    String jenisKelamin = "Laki-laki";
                    if(mahasiswa.getJenisKelamin().equalsIgnoreCase("P")){
                        jenisKelamin = "Perempuan";
                    }
                    o[2] = jenisKelamin;
                    o[3] = mahasiswa.getProgramStudi();
                    o[4] = mahasiswa.getJurusan();
                    model.addRow(o);
                }
            }
        }catch(Exception e){
            e.printStackTrace();
        }
    }
    
    private void cmdKeluar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdKeluar1ActionPerformed
        try {
            this.setClosed(true);
        } catch (PropertyVetoException ex) {
        }
    }//GEN-LAST:event_cmdKeluar1ActionPerformed

    private void cmdTambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdTambahActionPerformed
        FrmMain.openForm(new FrmMahasiswaDetail(""), "Editor Mahasiswa");
        try {
            this.setClosed(true);
        } catch (PropertyVetoException ex) {
        }
    }//GEN-LAST:event_cmdTambahActionPerformed

    private void cmdUbahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdUbahActionPerformed
        int selected = tableMahasiswa.getSelectedRow();
        if(selected==-1){
            JOptionPane.showMessageDialog(rootPane, "Anda belum memilih data yang akan diubah.");
            return;
        }
        
        FrmMain.openForm(new FrmMahasiswaDetail(model.getValueAt(selected, 0).toString()), "Editor Mahasiswa");
        try {
            this.setClosed(true);
        } catch (PropertyVetoException ex) {
        }
    }//GEN-LAST:event_cmdUbahActionPerformed

    private void cmdCariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdCariActionPerformed
        loadData();
    }//GEN-LAST:event_cmdCariActionPerformed

    private void cmdHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdHapusActionPerformed
        int selected = tableMahasiswa.getSelectedRow();
        if(selected==-1){
            JOptionPane.showMessageDialog(rootPane, "Anda belum memilih data yang akan dihapus.");
            return;
        }
        String nim = tableMahasiswa.getValueAt(selected, 0).toString();
        String nama = tableMahasiswa.getValueAt(selected, 1).toString();
        int c = JOptionPane.showConfirmDialog(rootPane, "Anda yakin akan menghapus data ini?\n > Nim    : "+nim+"\n > Nama : "+nama, "Konfirmasi", JOptionPane.YES_NO_OPTION);
        if(c==JOptionPane.YES_OPTION){
            boolean success = DbMahasiswa.hapusData(nim);
            if(success){
                loadData();
                JOptionPane.showMessageDialog(null, "Data telah dihapus.", "Infomasi", JOptionPane.INFORMATION_MESSAGE);
            }
        }
    }//GEN-LAST:event_cmdHapusActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cmdCari;
    private javax.swing.JButton cmdHapus;
    private javax.swing.JButton cmdKeluar;
    private javax.swing.JButton cmdKeluar1;
    private javax.swing.JButton cmdTambah;
    private javax.swing.JButton cmdUbah;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tableMahasiswa;
    private javax.swing.JTextField txtCari;
    // End of variables declaration//GEN-END:variables
}

